# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cabbazar_user' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cabbazar_user

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  target 'cabbazar_user-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cabbazar_userTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cabbazar_user-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for cabbazar_user-tvOS

  end

end


